from datetime import datetime
from html import escape
from pathlib import Path


class HtmlReporter:
    """Generates an HTML report from a trace analysis report dictionary."""

    def export(self, report: dict, output_file: str) -> str:
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        top_can_rows = self._build_top_can_table(report.get("top_can_ids", []))

        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>EV Trace Analysis Report</title>
<style>
body {{ font-family: Arial, Helvetica, sans-serif; margin: 40px; background-color: #f4f6f8; color: #333333; }}
.container {{ background-color: white; border-radius: 10px; padding: 30px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
h1 {{ color: #003366; }}
h2 {{ color: #003366; border-bottom: 2px solid #003366; padding-bottom: 5px; }}
.summary-grid {{ display: grid; grid-template-columns: 250px auto; row-gap: 10px; margin-top: 20px; }}
.label {{ font-weight: bold; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
th {{ background-color: #003366; color: white; }}
th, td {{ border: 1px solid #d0d0d0; padding: 8px; text-align: left; }}
tr:nth-child(even) {{ background-color: #f8f8f8; }}
.footer {{ margin-top: 30px; font-size: 12px; color: #666666; }}
</style>
</head>
<body>
<div class="container">
<h1>EV Trace Analysis Report</h1>
<p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
<h2>File Information</h2>
<div class="summary-grid">
<div class="label">File Name</div><div>{escape(str(report.get('file_name', '')))}</div>
<div class="label">Message Count</div><div>{report.get('message_count', 0):,}</div>
<div class="label">Unique CAN IDs</div><div>{report.get('unique_id_count', 0):,}</div>
<div class="label">Channel Count</div><div>{report.get('channel_count', 0)}</div>
<div class="label">Channels</div><div>{escape(str(report.get('channels', [])))}</div>
<div class="label">Duration</div><div>{escape(str(report.get('duration_text', '')))}</div>
<div class="label">Duration (Seconds)</div><div>{report.get('duration_seconds', 0)}</div>
</div>
<h2>Top CAN IDs</h2>
<table>
<tr><th>CAN ID</th><th>Message Count</th></tr>
{top_can_rows}
</table>
<div class="footer">Generated by EV Trace Processor</div>
</div>
</body>
</html>
"""

        output_path.write_text(html, encoding='utf-8')
        return str(output_path)

    @staticmethod
    def _build_top_can_table(top_can_ids: list) -> str:
        rows = []
        for item in top_can_ids:
            can_id = escape(str(item.get('can_id_hex', '')))
            count = item.get('count', 0)
            rows.append(f"<tr><td>{can_id}</td><td>{count:,}</td></tr>")
        return ''.join(rows)
